### ISSUE TITLE
More fodder for preparing a PR and responding to review

### ISSUE THREAD

**Issue by jennybc** [DavisVaughan/tidyverse-principles-of-code-review#3]
This is something I wrote elsewhere that we might be able to incorporate here. There's some overlap with what's already in the README, but I want to park this here, for future incorporation.

* Description contains enough of a problem statement and analysis to orient reviewer quickly, esp. if the related issue does not provide this.
* Test is written in a way that’s consistent with the appropriate combination of the surrounding tests, the tidyverse style guide, styler package. Applies to:
  - Nitpicky stuff like whitespace and indentation
  - Approaches to the creation (and cleanup) of test objects
  - Is the test minimal and sufficient? Is the test object as simple as it can be to fulfill its role? Is the function-call-under-test as simple as it can be to satisfy the test’s intent?
* Have you gone into a skeptical, adversarial mindset and considered if you’ve covered the relevant code branches and edge cases?
* Add NEWS bullet, if applicable
* Do PR title and NEWS bullet use language that’s crisp and specific? 
* Are the right hyperlinks and magic words in place to create connections to or close relevant issues/PRs?
* If there are areas that are anticipated to attract a reviewer’s comment, can you eliminate one iteration and proactively address that concern? For example, make the fix, add the code comment, insert helpful context by commenting (reviewing) on specific line(s) of the PR.
* Direct the reviewer to areas that are especially tricky or where feedback is especially needed by commenting (reviewing) on specific line(s) of the PR.
* Meta:
  - When reacting to specific feedback, try to identify if there is a more general take-away that can inform the next PR.
  - If it’s hard to see the point of a requested change, ask if there’s a bigger picture.
  - Mechanical, nit-picky problems with Git/GitHub/code style shouldn’t come up repeatedly. After the first 1-2 instances, add it to a literal or metaphorical checklist.
  - It is often a good idea to open a draft PR. Then sleep on it. Look over it again with fresh eyes. Make refinements, then ask for review.
  - Even if you’ve requested review, if you’re not completely blocked, you can continue to develop the PR in the meantime.

**Comment by DavisVaughan** [comment]
> Test is written in a way that’s consistent with the appropriate combination of the surrounding tests, the tidyverse style guide, styler package. Applies to:

- Is the package using testthat 3 features yet? If not, don't try and force it unless the PR is specifically about updating to testthat 3.
- Is the package using `test_that()` or `describe(it())`? Stick with whatever pattern is already being used.

> Have you gone into a skeptical, adversarial mindset and considered if you’ve covered the relevant code branches and edge cases?

This is somehow related to "be your own reviewer" and works nicely in combination with the idea of taking a break and coming back to the PR after not looking at it for an hour / letting it sit overnight before sending it in.

> Even if you’ve requested review, if you’re not completely blocked, you can continue to develop the PR in the meantime.

What do you mean here? Typically I only request review after I'm fairly certain I'm "done" with the PR or am blocked and need advice (which also counts as a sort of "done for now" state).

**Comment by jennybc** [comment]
>> Even if you’ve requested review, if you’re not completely blocked, you can continue to develop the PR in the meantime.
>
> What do you mean here? Typically I only request review after I'm fairly certain I'm "done" with the PR or am blocked and need advice (which also counts as a sort of "done for now" state).

I just mean that, once one tags a reviewer, you don't have to completely cease work on the PR . If the reviewer can't get to it right away, it's still possible to continue working on it and improving it, which might even make it easier to review and merge when the reviewer gets there.

**Comment by DavisVaughan** [comment]
Basically all handled in some way in https://davisvaughan.github.io/code-review/
