### ISSUE TITLE
Thoughts from human code reviews part 1

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/tidyverse-principles-of-code-review#4]
https://mtlynch.io/human-code-reviews-1/

---

Incentives for quickly getting to code reviews:

> When you start reviews immediately, you create a virtuous cycle. Your review turnaround becomes purely a function of the size and complexity of the author’s changelist. This incentivizes authors to send small, narrowly-scoped changelists. These are easier and more pleasant for you to review, so you review them faster, and the cycle continues.

Anything we can do to encourage "small narrowly-scoped changelists" is a good thing

More importantly, reviewing _slowly_ heavily incentives larger PRs

> Imagine that your teammate implements a new feature that requires 1,000 lines of code changes. If they know you can review a 200-line changelist in about 2 hours, they can break their feature into changelists of about 200 lines each and get the whole feature checked in within a day or two. If, however, you take a day to do all code reviews, regardless of size, now it takes a week to get that feature checked in. Your teammate doesn’t want to sit around for a week, so they’re incentivized to send larger code reviews, like 500-600 lines each. These are more costly to review and yield poorer feedback because it’s more difficult to keep context on a 600-line change than a 200-line change. 

---

If you expect multiple rounds of review, focus on high level details in the first round, because any low level details like naming / syntax might change anyways after incorporating large high level changes

---

Avoiding `you`:

"you misspelled `sucessfully`" can be viewed as passive aggresive:

Alternatives:
- you -> we, "can we fix this misspelling?"
- take you out entirely: `sucessfully -> successfully`

---

Command vs Request:

"Move the `foo()` function to its own file."

"Can we move `foo()` to its own file?"

One invites feedback and is a suggestion, the other can be seen as pushy.

**Comment by hfrick** [comment]
Point 5 of ["Be generous with code examples"](https://mtlynch.io/human-code-reviews-1/#be-generous-with-code-examples) is also pretty helpful IMO. I would say making use of the GitHub feature to suggest changes also falls in this category, especially for small changes. So instead of pointing out a typo, it's more helpful to just fix it in a suggestion and the author can commit those suggested changes right away.
