### ISSUE TITLE
Thoughts from human code review part 2

### ISSUE THREAD

**Issue by DavisVaughan** [DavisVaughan/tidyverse-principles-of-code-review#5]
Avoiding PR Dread (this feels like a section in itself)

Do you ever get into that situation where you have a PR you need to review, but you just keep ignoring it and doing other things? We want to avoid that situation at all costs

- You want to do anything possible to avoid getting into a stalemate between the reviewer and author. This is productive for no one, and often ends up making the two people mad at each other. If you recognize this situation, mutually decide to bring in a third person, or consider discussing over video call - where it is much easier to convey empathy and clearly explain arguments. I actively move towards a video call or Slack if I realize that the reviewer isn't quite understanding what I'm trying to say, but I can't see an easy way to explain it differently.
- Avoiding dread is related to keeping the PR sizes small. But small PRs are also reliant on fast reviewers (otherwise someone will send in a big PR to avoid multiple long rounds of small PRs)

---

> I privately think of the code in terms of letter grades, from A to F. When I receive a changelist that starts at a D, I try to help the author bring it to a C or a B-. Not perfect, but good enough.

I'm not quite sure how I feel about this. I feel like ideally PRs are only merged once they get to A status, even if it takes time.

I as the maintainer become responsible for any merged pull request, so I feel like I have some say in the perceived quality of code that I allow to be merged in.

Maybe after 1-2 rounds of review, you thanks the reviewer profusely for their contribution, encourage them to submit more changes in the future, and then offer to take over the PR to finish it off?

---

PR review is also a nice time to mention when things are working well. Like, if you and the PR author worked together recently on a new error reporting pattern, and then that pattern shows up again as a nice solution in their newest PR, take the time to call that out as something that was nice to see. If you do this enough times you can sometimes isolate patterns that can be extracted into standalone functions or helpers.

---

"Sincere praise" (as the author called it) is _super_ important when reviewing the work of new team members. They are often quite nervous about sending in pull requests, so offering some praise in combination with constructive feedback is a great way to show them that you are all in this together, and that you are noticing their growth.

---

This is a great section:
[Grant approval when remaining fixes are trivial](https://mtlynch.io/human-code-reviews-2/#grant-approval-when-remaining-fixes-are-trivial)

Lionel and I have this working relationship where we approve each others PRs immediately when we don't have any "significant" comments.

I think if you are working with an experienced PR author, your default should be to try to approve alongside the first round of review unless you strongly disagree with something. You can always silently check the changes they made in response to your review, and then you only ever need to bring something up if you happen to catch something egregious. 

For junior PR authors, I think it makes sense to withhold review until a second round, giving you time to correct any mistakes they might have made while interpreting your first round of review.

---

For the absolute worst stalemates, appoint a senior "Benevolent Dictator" that may or may not be the author/reviewer that can kindly break ties. The team needs to agree that if this person makes a decision, and the code change isn't life or death, then they should accept the change and move on. It is the job of the Benevolent Dictator to break stalemates in a kind way that doesn't harm either party. It should be very rare that this would have to be invoked.

---

I think it would be nice to develop a culture where it isn't weird or insulting if the author of the package "takes over" a pull request to finish it off. Sometimes it is just faster for the package author to do this if they are trying to churn through a number of pull requests / issues. Sometimes the package author just intrinsically knows more about the package, and needs to do some "technical details" to keep everything in sync, even if those aren't strictly related to the core ethos of the PR. I think PR authors should be okay with this, and respect that the package author has to maintain that codebase in the long run, so they should get the final say in how a PR looks before getting merged.

That doesn't mean that your PR wasn't valuable. It likely fixed a bug or added a new feature, which is very valuable! Don't be discouraged or insulted if the package author tweaks some minutiae about the code before merging it. Again, remember that they are likely the one that has to maintain your PR in the long run.

**Comment by DavisVaughan** [comment]
If you are reviewing, review The Thing. We often say that a PR should do One Thing, but as the reviewer you should also only review that One Thing

**Comment by DavisVaughan** [comment]
Define what Internal contributor vs External contributor means. Because that impacts whether or not you just "finish off" a pull request for someone when it is most of the way there

Internal = package maintainers or high touch contributors
External = other members of the R community, or team members that don't work on your package

**Comment by jennybc** [comment]
> When I receive a changelist that starts at a D, I try to help the author bring it to a C or a B-. Not perfect, but good enough.

Another useful mindset for making forward progress is reflecting on the letter grade of the code / functionality *before* the PR. A B- PR might still be an improvement worth making, if we're starting at C+.
